### PR TITLE
Fix: Type terragrunt-run-all is not supported

### LINKED ISSUE #220: Type terragrunt-run-all is not supported
**Describe the bug**
When running terragrunt with `-type=terragrunt-run-all` we get the following error:
```
invalid type terragrunt-run-all, must be either 'terratag' or 'terragrunt'

```

**To Reproduce**
Run `terratag -tags="{\"env0_environment_id\":\"37645cf4-1cb3-4d76-b8c9-d6825fe8674d\",\"env0_project_id\":\"8c4735e9-f955-430a-838c-c0fa652efcb2\"}" -rename=false -type=terragrunt-run-all`

**Expected behavior**
Tag the relevant resources

### PR DESCRIPTION
**Pull request by TomerHeber**
fixes #220

### CODE REVIEW

File: cli/args.go [hunk 1]
```diff
@@ -29,8 +29,8 @@ func validate(args Args) error {
 		return errors.New("missing tags")
 	}
 
-	if args.Type != string(common.Terraform) && args.Type != string(common.Terragrunt) {
-		return fmt.Errorf("invalid type %s, must be either 'terratag' or 'terragrunt'", args.Type)
+	if args.Type != string(common.Terraform) && args.Type != string(common.Terragrunt) && args.Type != string(common.TerragruntRunAll) {
+		return fmt.Errorf("invalid type %s, must be either 'terratag', 'terragrunt', or 'terragrunt-run-all'", args.Type)
```
Comment (Yossi-kerner) [inline cli/args.go:33]: I guess `terratag` is a type here?

File: .github/workflows/ci.yml [hunk 2]
```diff
@@ -90,20 +90,20 @@ jobs:
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v3
         with:
-          terraform_version: 1.2.5
+          terraform_version: 1.11.4
```
Comment (Yossi-kerner) [inline .github/workflows/ci.yml:93]: why do we need this?

File: terratag_test.go [hunk 3]
```diff
@@ -122,6 +122,32 @@ func TestTerragruntWithCache(t *testing.T) {
...
+
+	in := entryDir + "/in"
+	out := entryDir + "/out"
+
+	if err := os.RemoveAll(out); err != nil {
+		t.Fatalf("failed to remove out directory: %s %s", out, err.Error())
+	}
+
+	if err := copy.Copy(in, out); err != nil {
+		t.Fatalf("failed to in directory to out directory: %s", err.Error())
```
Comment (Yossi-kerner) [inline terratag_test.go:142]:
```suggestion
		t.Fatalf("failed to copy in directory to out directory: %s", err.Error())
```
?

**Review by Yossi-kerner — COMMENTED** [review]
All in all looking good left some small comments. I need to check about the tf version upgrade just to make sure

File: cli/args.go (hunk 1 above)
Comment (TomerHeber) [reply cli/args.go:33]: yeah good catch. lemme fix it.

File: .github/workflows/ci.yml (hunk 2 above)
Comment (TomerHeber) [reply .github/workflows/ci.yml:93]: I upgraded the terraform version used for terragrunt tests.

File: cli/args.go (hunk 1 above)
Comment (TomerHeber) [reply cli/args.go]: fixed.

**Review by Yossi-kerner — APPROVED** [review]
