### PR TITLE
Fix: aws_autoscaling_group that is using tags can't work with terratag

### LINKED ISSUE #101: aws_autoscaling_group that is using tags can't work with terratag
Looks like you count on the fact that only the `tag` way to add tags to `autoscaling_group`. We use some modules that defines the `autoscaling_group` for us such as `consul_cluster` for example and we do not control if they use `tags` or `tag`.

For this we need to custom method that tags `autoscaling_group` to use tags or tag based on the existing code.

Error example:
```
╷
│ Error: Conflicting configuration arguments
│
│   with module.consul_cluster.module.consul_cluster.aws_autoscaling_group.autoscaling_group,
│   on .terraform/modules/consul_cluster.consul_cluster/modules/consul-cluster/main.terratag.tf line 39, in resource "aws_autoscaling_group" "autoscaling_group":
│   39:   tags = flatten(
│   40:     [
│   41:       {
│   42:         key                 = "Name"
│   43:         value               = var.cluster_name
│   44:         propagate_at_launch = true
│   45:       },
│   46:       {
│   47:         key                 = var.cluster_tag_key
│   48:         value               = var.cluster_tag_value
│   49:         propagate_at_launch = true
│   50:       },
│   51:       var.tags,
│   52:     ]
│   53:   )
│
│ "tags": conflicts with tag
```

### PR DESCRIPTION
**Pull request by TomerHeber**
Added support for the "tags" usecase.
Added the use-case to the integration tests.
Fixed (major) issues with the integration tests.

Fixes #101

### CODE REVIEW

File: internal/tagging/aws.go [hunk 1]
```diff
@@ -1,14 +1,43 @@
...
+		expression = strings.TrimSuffix(expression, "${")
+
+		key := "local." + tag_keys.GetTerratagAddedKey(args.Filename)
+		newTagsValue := "flatten([" + key + "," + expression + "])"
+
+		newTags := ParseHclValueStringToTokens(newTagsValue)
+
+		args.Block.Body().SetAttributeRaw("tags", newTags)
+	} else {
+		// no "tags" interpolation is used, but rather multiple instances of a "tag" block
```
Comment (TomerHeber) [inline internal/tagging/aws.go:36]: This was the default use-case before adding the if-else.

File: internal/tagging/aws.go [hunk 2]
```diff
@@ -1,14 +1,43 @@
...
 	// https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html
-	if err := convert.AppendTagBlocks(args.Block, args.Tags); err != nil {
+
+	var tagsMap map[string]string
+	if err := json.Unmarshal([]byte(args.Tags), &tagsMap); err != nil {
 		return nil, err
 	}
 
+	tagsAttr := args.Block.Body().GetAttribute("tags")
+	if tagsAttr != nil {
```
Comment (TomerHeber) [inline internal/tagging/aws.go:21]: There is "tags" attribute.

File: internal/tagging/aws.go [hunk 3]
```diff
@@ -1,14 +1,43 @@
...
+		// "tags" interpolation is used
+		tokens := tagsAttr.Expr().BuildTokens(hclwrite.Tokens{})
+		expression := strings.TrimSpace(string(tokens.Bytes()))
+		// may be wrapped with ${ } in TF11
+		expression = strings.TrimPrefix(expression, "${")
+		expression = strings.TrimSuffix(expression, "${")
+
+		key := "local." + tag_keys.GetTerratagAddedKey(args.Filename)
+		newTagsValue := "flatten([" + key + "," + expression + "])"
```
Comment (TomerHeber) [inline internal/tagging/aws.go:30]: Basically, it's going to be something like this:
```
tags = flatten([local.terratag_added_main, flatten(
    [
      {
        key                 = "Name"
        value               = var.cluster_name
        propagate_at_launch = true
      },
      {
        key                 = var.cluster_tag_key
        value               = var.cluster_tag_value
        propagate_at_launch = true
      },
      var.tags,
    ]
  )])

```

**Comment by TomerHeber** [comment]
still missing test. Wanted some feedback first.

File: internal/tagging/aws.go (hunk 3 above)
Comment (yaronya) [reply internal/tagging/aws.go:30]: Guessing the double `flatten` in your example is redundant, right?

Comment (TomerHeber) [reply internal/tagging/aws.go:30]: The original was:
```
flatten(
    [
      {
        key                 = "Name"
        value               = var.cluster_name
        propagate_at_launch = true
      },
      {
        key                 = var.cluster_tag_key
        value               = var.cluster_tag_value
        propagate_at_launch = true
      },
      var.tags,
    ]
  )
```

I this case double flatten is required.

File: internal/tagging/aws.go (hunk 2 above)
Comment (TomerHeber) [inline internal/tagging/aws.go:21]: Note:
this fix will not work for 0.11 - assuming this is okay since 0.11 was released 5 years ago.

File: terratag_test.go [hunk 4]
```diff
@@ -153,19 +153,28 @@ func testTerraformWithFilter(t *testing.T, version string, filter string) {
 	}
 }
 
-func itShouldGenerateExpectedTerratagFiles(suiteDir string, g *GomegaWithT) {
-	expectedPattern := suiteDir + "/expected/**/*.terratag.tf"
+func itShouldGenerateExpectedTerratagFiles(entryDir string, g *GomegaWithT) {
```
Comment (TomerHeber) [inline terratag_test.go:156]: There was alot of work towards this function.
When updating a test, I noticed that tests didn't really compare files.
This is now fixed. I had to do some fixes/changes to make all the tests work.

File: terratag_test.go [hunk 5]
```diff
@@ -153,19 +153,28 @@ func testTerraformWithFilter(t *testing.T, version string, filter string) {
...
+		expectedPattern = strings.Split(entryDir, "/out/")[0] + "/expected/**/*.tf"
+		expectedTerratag, _ = doublestar.Glob(expectedPattern)
+	}
+	actualTerratag, _ = doublestar.Glob(entryDir + "/*.tf")
+	if len(actualTerratag) == 0 {
+		actualTerratag, _ = doublestar.Glob(entryDir + "/**/*.tf")
+	}
 	actualTerratag = filterSymlink(actualTerratag)
 
+	g.Expect(len(actualTerratag)).Should(BeNumerically(">", 0))
```
Comment (TomerHeber) [inline terratag_test.go:171]: these two g.Expect verify that we found the files. Before it was 0. Making sure it's larger than 0 - otherwise fail.

File: test/fixture/terraform_11/config.yaml [hunk 6]
```diff
@@ -1,7 +1,4 @@
 suites:
-  - aws_autoscaling_group
```
Comment (TomerHeber) [inline test/fixture/terraform_11/config.yaml:2]: removed some tests.
 aws_autoscaling_group - will fail (not supported). I think it's okay because 0.11 is from 2017 (old).
The other two I can get fixed. But not sure it's worth the effort, so I just removed them.
(I doubt anyone is still using 0.11).

File: test/fixture/terraform_12/config.yaml [hunk 7]
```diff
@@ -5,12 +5,12 @@ suites:
   - aws_tags_map
   - azurerm_kubernetes_cluster
   - azurerm_tags_map
-  - azurestack_tags_map_11
+  - azurestack_tags_map
```
Comment (TomerHeber) [inline test/fixture/terraform_12/config.yaml:8]: not sure why I set them for _11.
They should run the regular version.

File: test/tests/aws_autoscaling_group/expected/main.terratag.tf [hunk 8]
```diff
@@ -70,6 +70,48 @@ EOF
     propagate_at_launch = true
   }
 }
+
+resource "aws_autoscaling_group" "bar_tags" {
```
Comment (TomerHeber) [inline test/tests/aws_autoscaling_group/expected/main.terratag.tf:74]: This tests the new use-case. (tags = [...]).

File: test/tests/aws_azure/expected/main.terratag.tf [hunk 9]
```diff
@@ -21,9 +21,9 @@ provider "aws" {
 resource "azurerm_resource_group" "should_have_tags" {
   name     = "example-resources"
   location = "West Europe"
-  tags = merge(tomap({
+  tags = merge({
```
Comment (TomerHeber) [inline test/tests/aws_azure/expected/main.terratag.tf:24]: tomap is for 0.11
modified all tests...

File: test/tests/azurestack_tags_map/expected/main.terratag.tf [hunk 10]
```diff
@@ -6,6 +6,10 @@ terraform {
   }
 }
 
+provider "azurestack" {
```
Comment (TomerHeber) [inline test/tests/azurestack_tags_map/expected/main.terratag.tf:9]: this is now required.

File: test/fixture/terraform_12/config.yaml [hunk 11]
```diff
@@ -5,12 +5,10 @@ suites:
   - aws_tags_map
```
Comment (TomerHeber) [inline test/fixture/terraform_12/config.yaml:5]: remove some tests in here as well.
compatibility issue with existing providers. Not worth the effort to fix (0.12 is an old version).

**Comment by yaronya** [comment]
@TomerHeber FYI I attached the relevant GH issue to this PR

**Review by tomer-landesman — APPROVED** [review]
I don't know go that well, but all in all looks good :)
