### PR TITLE
Fix: AWS EC2 volume tag errors

### LINKED ISSUE #190: AWS EC2 volume tag errors
**Describe the bug**
After the merging of #187 for #186, we get `"root_block_device.0.tags": conflicts with volume_tags` when running `terraform plan` after running terratag.

**To Reproduce**
A minimal Terraform configuration reproducing the issue:  
```terraform
resource "aws_instance" "test" {
  ami                         = "ami-0f5daaa3a7fb3378b"
  instance_type               = "t2.micro"
  subnet_id                   = "subnet-0000000000000"
  vpc_security_group_ids      = ["sg-0000000000000"]

  root_block_device {
    volume_size           = 8
    tags = {
      Name = "test"
    }
  }
}

```

run 
```
terratag -tags="terratag=yes"
terraform plan
```

**Expected behavior**
`terraform plan` should add the `terratag=yes` tag and the original `Name=test` test to the ec2 root volume

**Screenshots**
We are getting the following error
```
terraform plan
╷
│ Error: Conflicting configuration arguments
│
│   with aws_instance.test,
│   on main.terratag.tf line 9, in resource "aws_instance" "test":
│    9:     tags = {
│   10:       Name = "test"
│   11:     }
│
│ "root_block_device.0.tags": conflicts with volume_tags
```

**Desktop (please complete the following information):**
 - Terraform version: 1.5.7
 - terratag version: 0.3.2

**Additional context**
The result tf file after running terratag is
```
resource "aws_instance" "test" {
  ami                    = "ami-0f5daaa3a7fb3378b"
  instance_type          = "t2.micro"
  subnet_id              = "subnet-0000000000000"
  vpc_security_group_ids = ["sg-0000000000000"]

  root_block_device {
    volume_size = 8
    tags = {
      Name = "test"
    }
  }
  tags        = local.terratag_added_main
  volume_tags = local.terratag_added_main
}

locals {
  terratag_added_main = {"terratag"="yes"}
}
```

**Workaround**

ditching the `root_block_device[0].tags`, and instead putting them as `volume_tags`

### PR DESCRIPTION
**Pull request by TomerHeber**
resolves #190 

Does not add tags to volume_tags if root_block_device block is used. (Per documentation they conflict).
I'm now also tagging root_block_device. I hope it makes sense.

### CODE REVIEW

File: internal/tagging/aws.go [hunk 1]
```diff
@@ -18,13 +18,24 @@ func tagAwsInstance(args TagBlockArgs) (*Result, error) {
...
 	swappedTagsStrings = append(swappedTagsStrings, tagBlock)
 
-	volumeTagBlockArgs := args
-	volumeTagBlockArgs.TagId = "volume_tags"
-	volumeTagBlock, err := TagBlock(volumeTagBlockArgs)
-	if err != nil {
-		return nil, err
+	rootBlockDevice := args.Block.Body().FirstMatchingBlock("root_block_device", nil)
+
+	if rootBlockDevice == nil {
```
Comment (TomerHeber) [inline internal/tagging/aws.go:23]: if the block does not exist - tag volume_tags as usual...

File: internal/tagging/aws.go [hunk 2]
```diff
@@ -18,13 +18,24 @@ func tagAwsInstance(args TagBlockArgs) (*Result, error) {
...
+		volumeTagBlockArgs := args
+		volumeTagBlockArgs.TagId = "volume_tags"
+		volumeTagBlock, err := TagBlock(volumeTagBlockArgs)
+		if err != nil {
+			return nil, err
+		}
+		swappedTagsStrings = append(swappedTagsStrings, volumeTagBlock)
+	} else {
```
Comment (TomerHeber) [inline internal/tagging/aws.go:31]: I decided to add  tags to root block device. I hope it makes sense.

File: test/tests/aws_instance_volume_tags/expected/main.tf [hunk 3]
```diff
@@ -16,14 +16,27 @@ resource "aws_instance" "ubuntu" {
...
   }, local.terratag_added_main)
   volume_tags = local.terratag_added_main
 }
 
+resource "aws_instance" "ubuntu2" {
+  ami               = "dasdasD"
+  instance_type     = "t3.micro"
+  availability_zone = "us-west-2"
+
+  root_block_device {
```
Comment (yaronya) [inline test/tests/aws_instance_volume_tags/expected/main.tf:31]: Can you please also add the volume_tags block here and make sure it's not altered?

Comment (TomerHeber) [reply test/tests/aws_instance_volume_tags/expected/main.tf:31]: You can't... it will create a confilct.
volume_tags should have been added, but wasn't added because root_block_device exist.

File: internal/tagging/aws.go [hunk 4]
```diff
@@ -18,13 +18,24 @@ func tagAwsInstance(args TagBlockArgs) (*Result, error) {
 	}
 	swappedTagsStrings = append(swappedTagsStrings, tagBlock)
 
-	volumeTagBlockArgs := args
-	volumeTagBlockArgs.TagId = "volume_tags"
-	volumeTagBlock, err := TagBlock(volumeTagBlockArgs)
-	if err != nil {
-		return nil, err
+	rootBlockDevice := args.Block.Body().FirstMatchingBlock("root_block_device", nil)
```
Comment (terenho-jobber) [inline internal/tagging/aws.go:21]: I suspect we have a similar problem with `ebs_block_device` too

File: test/tests/aws_instance_volume_tags/expected/main.tf (hunk 3 above)
Comment (TomerHeber) [reply test/tests/aws_instance_volume_tags/expected/main.tf:30]: @yaronya - based on the documentation, I've made larger changes. (it's less straighforward than I initially assumed).
Please recheck.

See the tag guide:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#tag-guide

File: internal/tagging/aws.go [hunk 5]
```diff
@@ -18,13 +18,64 @@ func tagAwsInstance(args TagBlockArgs) (*Result, error) {
...
+		// tag 'volume_tags'.
+		volumeTagBlockArgs := args
+		volumeTagBlockArgs.TagId = "volume_tags"
+		volumeTagBlock, err := TagBlock(volumeTagBlockArgs)
+		if err != nil {
+			return nil, err
+		}
+		swappedTagsStrings = append(swappedTagsStrings, volumeTagBlock)
+	} else {
+		// tag 'root_block_device' block (if it exists).
```
Comment (TomerHeber) [inline internal/tagging/aws.go:53]: 0..1

File: internal/tagging/aws.go [hunk 6]
```diff
@@ -18,13 +18,64 @@ func tagAwsInstance(args TagBlockArgs) (*Result, error) {
...
+			tagBlock, err := TagBlock(args)
+			if err != nil {
+				return nil, err
+			}
+			swappedTagsStrings = append(swappedTagsStrings, tagBlock)
+			args.Block = origArgsBlock
+		}
+
+		// tag 'ebs_block_device' blocks (if any exist).
+		for _, block := range args.Block.Body().Blocks() {
```
Comment (TomerHeber) [inline internal/tagging/aws.go:66]: 0..*

File: internal/tagging/aws.go [hunk 7]
```diff
@@ -18,13 +18,64 @@ func tagAwsInstance(args TagBlockArgs) (*Result, error) {
...
+		volumeTagBlockArgs.TagId = "volume_tags"
+		volumeTagBlock, err := TagBlock(volumeTagBlockArgs)
+		if err != nil {
+			return nil, err
+		}
+		swappedTagsStrings = append(swappedTagsStrings, volumeTagBlock)
+	} else {
+		// tag 'root_block_device' block (if it exists).
+		if rootBlockDevice != nil {
+			origArgsBlock := args.Block
```
Comment (TomerHeber) [inline internal/tagging/aws.go:55]: for swapping back in line 66.

File: internal/tagging/aws.go
Comment (TomerHeber) [inline internal/tagging/aws.go:1]: @yaronya - please review the input vs expected files.
Need to make sure it's correct, and no missing use-cases.

(tofu plan is successful).

**Comment by RLRabinowitz** [comment]
Tiny note - Looking at the [note](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#volume_tags) of `volume_tags`, there might be some inconsistent behaviour if the user is adding tags of his own to attached `aws_ebs_volume`.

Might be something worth considering. I don't think we can really tell if there's an attached aws_ebs_volume, so maybe adding `volume_tags` here is good enough

**Comment by TomerHeber** [comment]
> Tiny note - Looking at the [note](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#volume_tags) of `volume_tags`, there might be some inconsistent behaviour if the user is adding tags of his own to attached `aws_ebs_volume`.
> 
> Might be something worth considering. I don't think we can really tell if there's an attached aws_ebs_volume, so maybe adding `volume_tags` here is good enough

Yeah - I saw it as well. I guess the user will have to fix it manually. (?)

File: internal/tagging/aws.go
Comment (chpl) [reply internal/tagging/aws.go:1]: Hey @TomerHeber 
we think that the logic should be as following
- if there's volume_tags (even if there's no `root_block_device` or `ebs_block_device`)
  - add tags to it
- else
  - if there's any `ebs_block_device` add tags to it
  - add tags to the `root_block_device` even if it's not exists

Comment (chpl) [reply internal/tagging/aws.go:1]: from this
```hcl
resource "aws_instance" "test" {
  ami           = "ami-0f403e3180720dd7e"
  instance_type = "t3a.nano"
  volume_tags = {
    "c" = "d"
  }
  root_block_device {
    volume_type = "gp3"
  }
  ebs_block_device {
    device_name = "/dev/xvdb"
    volume_type = "gp3"
  }
}
```
to this
```hcl
resource "aws_instance" "test" {
  ami           = "ami-0f403e3180720dd7e"
  instance_type = "t3a.nano"
  volume_tags = merge({
    "c" = "d"
  }, local.terratag_added_main)
  root_block_device {
    volume_type = "gp3"
  }
  ebs_block_device {
    device_name = "/dev/xvdb"
    volume_type = "gp3"
  }
}
```

Comment (chpl) [reply internal/tagging/aws.go:1]: from this
```hcl
resource "aws_instance" "test" {
  ami           = "ami-0f403e3180720dd7e"
  instance_type = "t3a.nano"
  ebs_block_device {
    device_name = "/dev/xvdb"
    volume_type = "gp3"
  }
}
```
to this
```hcl
resource "aws_instance" "test" {
  ami           = "ami-0f403e3180720dd7e"
  instance_type = "t3a.nano"
  root_block_device {
    tags = local.terratag_added_main
  }
  ebs_block_device {
    device_name = "/dev/xvdb"
    volume_type = "gp3"
    tags = local.terratag_added_main
  }
}
```

Comment (TomerHeber) [reply internal/tagging/aws.go:1]: that makes sense.
I'll update the code. Thanks!

**Review by chpl — APPROVED** [review]
